# def sum(a,b):
#     return a+b
# print(sum(5,10))
# result = sum(10,20)
# print("sum of a and b is :", result)


# def sum(a,b):
#      s = a-b
#      return s
# print(sum(522,10))
# result = sum(1022222,20)
# print("sum of a and b is :", result)

def fun(name ='vedant', roll_no = 36):
    print("my name is ", name)
    print("my roll no is ", roll_no)
    return name, roll_no
result = fun()
print(result)